apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kubernetes resources to be managed by Kustomize
resources:
  - ../../app-data-layer/postgres/postgres-statefulset.yaml

# Infractucture Orquestation  (Longhorn Helm )
helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  releaseName: longhorn
  namespace: longhorn-system
  version: v1.5.3 # Especific Version
  valuesFile: ../../k8s/longhorn-base/values.yaml # Configuration Helm Charm
