apiVersion: v1
kind: Service
metadata:
  name: headless-postgres
  namespace: demo-app
  labels:
    service: svc-postgres
spec:
  ports:
  - port: 5432
   # name: web
  clusterIP: None
  selector:
    db: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: demo-app
spec:
  serviceName: "headless-postgres"
  replicas: 2 # Or more for a clustered setup
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      securityContext:
        # UID 999 ID 'postgres' USER AND GROUP
        runAsUser: 999  
        runAsGroup: 999
        fsGroup: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  db: postgres #
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: postgres
        image: postgres:15 # Use a specific PostgreSQL version
        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
          
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 5Gi

