apiVersion: v1
kind: Service
metadata:
  name: headless-postgres
  namespace: demo-app
  labels:
    service: svc-postgres
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    db: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: demo-app
spec:
  serviceName: "headless-postgres"
  replicas: 2 
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      securityContext:
        runAsUser: 999 
        runAsGroup: 999
        fsGroup: 999       
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: db
                  operator: In
                  values:
                  - postgres
              topologyKey: "kubernetes.io/hostname"
      
      containers:
      - name: postgres
        image: postgres:15 
        ports:
        - containerPort: 5432
          name: postgres

        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        volumeMounts:
        - name: postgres-data
          # CORRECCIÓN CRÍTICA: Montar el PVC directamente en la ubicación esperada por PostgreSQL ($PGDATA)
          mountPath: /var/lib/postgresql/data
          # Se elimina 'subPath' para que la raíz del volumen sea el directorio de datos
          
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 5Gi
