apiVersion: v1
data:
  db_name: database_name      # Remember in base64 format
  password: password_postgres # Remember in base64 format
  username: username_postgres # Remember in base64 format
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-app
